import requests
from bs4 import BeautifulSoup
import csv
import time
import random

def get_company_website(company_name):
    base_url = "https://www.goudengids.be/zoeken/"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
    }
    
    def search_and_extract(url, name):
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            return f"Failed to retrieve data for {name} (Status Code: {response.status_code})", "No website", "1 try"
        
        soup = BeautifulSoup(response.text, 'html.parser')
        result = soup.find('a', class_='absolute bottom-0 left-0 right-0 top-0 z-10')
        
        if result:
        # Check if href already contains "http" (indicating a full URL)
            href = result['href']
            if href.startswith("http"):
                detail_page_url = href
            else:
                detail_page_url = "https://www.goudengids.be" + href

            delay = random.uniform(2, 6)
            print(f"Sleeping for {delay:.2f} seconds...")
            time.sleep(delay)
            detail_response = requests.get(detail_page_url, headers=headers)
            if detail_response.status_code != 200:
                return f"Failed to retrieve detail page for {name} (Status Code: {detail_response.status_code})", "No website", "1 try"


            detail_soup = BeautifulSoup(detail_response.text, 'html.parser')
            company_name_on_goudengids = detail_soup.find('h1').text.strip()
            website_link = detail_soup.find('a', class_='outline-btn border-1')
            
            if website_link:
                website = website_link.get('href').split('?')[0]  # Remove UTM parameters
                if website.startswith('mailto:'):
                    return "No website", "1 try", company_name_on_goudengids
                else:
                    return website, "1 try", company_name_on_goudengids
            else:
                return "No website", "1 try", company_name_on_goudengids
        else:
            return None, "No website", "1 try"
    
    # Initial search with full company name
    search_url = base_url + company_name.replace(" ", "+")
    website, tries, company_name_on_goudengids = search_and_extract(search_url, company_name)
    
    if website is None or "Failed to retrieve" in website:
        # Try again with the first word of the company name
        first_word = company_name.split()[0]
        new_search_url = base_url + first_word
        website, tries, company_name_on_goudengids = search_and_extract(new_search_url, first_word)
        if website is not None and "Failed to retrieve" not in website:
            tries = "2 tries"
        else:
            website = "No search result found for " + company_name
            tries = "2 tries"

    return company_name, website, tries, company_name_on_goudengids
# List of companies here
companies = [
"LV TECHNICS",
"LACOLLONGE BELGIUM",
"TECCON",
"HENS",
"LAMOTE INFRA",
"LAMOTE AANNEMING",
"De Craemer",
"DECONINCK",
"M&M Contractors",
"Tasöz",
"ALGEMENE ELEKTRICITEITSWERKEN K. VERBEKE",
"GROUP ALBORO",
"S.S.B.",
"PETERS ELECTRO",
"ENTREPRISE DE CONSTRUCTION ET DE RENOVATION",
"B.R.I.S.",
"ELTA",
"Wouters",
"AKIN",
"AUGEN",
"Bureau d'Ingénieurs du Groupe Richard Flamée",
"MONTAGE ET MAINTENANCE INDUSTRIELS",
"Renika Infra b.v.b.a.",
"MULTI",
"progest",
"DU PUY GEBROEDERS BV",
"LOGIC-ELEC SA",
"FALCON",
"TARGET SERVICES",
"Ai5 INFRA",
"POLYDAK III",
"GESTION INTELLIGENTE DE MODULES D'IDENTIFICATION",
"TECAME BELGIUM",
"DCLEAN",
"AIR PLUS",
"Tuncel",
"GREEN PORT EQUIPMENT",
"MIK DEMOLITION",
"RDJ Drilling",
"TILTECH",
"MILTECH",
"SGGSB BOERMANS CONSTRUCT",
"AC-électrictié sprl",
"Ac-Electricité",
"CAGLA HAIR & BEAUTY",
"MUYLE ELECTRO MACHINERY DEVELOPMENT",
"G.B.M.",
"ALTECH 1973",
"OFFICE SUPPORT SERVICES",
"BERMAN",
"Arez",
"COEUS EUROPE EXPERTS",
"VULGA",
"Hydro - Jet HELLEBUYCK",
"Proffund",
"BJX INDUSTRIAL WORK ASSISTANCE",
"VERHOEVEN G.",
"AS & H bvba",
"ANOTEC",
"JMW Steelworks",
"DEVEUX ENVIRONNEMENT",
"EXKAL BELGIUM",
"S.L.S.",
"ATELIERS JOIRET",
"WENS HUGO",
"PANISOL",
"TECHNIWAL",
"BUREAU VOOR TECHNISCHE STUDIËN",
"WMB",
"The Cable Company",
"YILMAZ ELECTRICAL SOLUTIONS",
"BETTONVILLE ERIC",
"MultiTech",
"MONTECH",
"VH Facilities",
"GROUPE MORGAN SERVICES BELGIQUE",
"A.D.E.B. Verhuur bvba",
"VAN HECKE MECHANICS",
"Ignix Construct",
"V & V TECHNICS",
"Reliable Dynamic Technologies",
"COOLS",
"NEOLUX S.P.R.L.",
"HEIGHT SOLUTIONS",
"VAL ENERGIE 59 sarl",
"Balloo bvba",
"SOCIETE ANONYME DE VENTE DES EQUIPEMENTS TRANE",
"ASM bvba",
"IBO Construct",
"D.T.A. sa",
"DAHCOM",
"Techservices SRL",
"JCA",
"Galle Company",
"MK Technics Belgique",
"J.Y.C. CONCEPT",
"HERCULE  scrl",
"DE SCHUTTER JOS",
"Baltimore Aircoil Belgium",
"SCHRIJNWERKERIJ VAN MELE E. EN R.",
"HEMYTECH",
"PAUWELS",
"MontageElectroSanitair",
"ESSI",
"Van Loon, Franciscus",
"B.C.M.",
"MAINTENANCE, MECANIQUE ET SERVICES INDUSTRIELS",
"Quoniou, Frédéric",
"M.S.T. DELGADO",
"GREEN ROAD",
"CHIEFTAIN INVESTMENTS",
"ORICA BELGIUM",
"ISS OFFICE SUPPORT SERVICES",
"Travaux d'entretien et d'arrets en maintenance industrielle SARL",
"CLIMAPAC",
"Onderhoud De Jong Constructie",
"Signo SAS",
"AB Flex+ Group",
"CLEVER CLEANING",
"INDUMEC",
"KAZAN las- en montagewerken",
"ACK sprl",
"ALPHAPLAN",
"K-construction",
"CHIMTEX",
"Basil Construct",
"C.S. CONSTRUCTIONS",
"COMMUNICATIONS SERVICES AND TECHNOLOGY",
"HEROS",
"Proficlean nv",
"ENERSYS BELGIUM",
"NITELET",
"GODMETAAL",
"AMESCO",
"DE LILLE INFRA",
"Impact Multiservices",
"Belgisch Instituut voor Lastechniek Industrie, Institut Belge de la Soudure Industrie, Belgian Welding Institute Industry",
"Institut Belge de la Soudure - Belgisch Instituut voor Lastechniek",
"General Group",
"H & B Industries SA",
"Bouw- en Hydrowerken PEETERS",
"FREEZE AIR",
"AUTOMATION",
"EURO PAINT CLEAN",
"KEZCO GROUP",
"Sari Grondwerken",
"COLASSE",
"Matthys",
"L'ANTICORROSION",
"IS WERKEN",
"Oliver James Antwerp",
"KEON",
"Helco bvba",
"CABLE-LAN",
"N.C.P. IMMO",
"BDF Piping Services",
"C.M.G.",
"ARD'n MANAGEMENT",
"MICOTEC",
"The Airconditioning Company",
"GYSELINCK",
"REFRECO",
"SARINFRA",
"PHARA Flex",
"ELMOTECH",
"LEROY",
"Maes Rent & Sale",
"ETS TASPINAR",
"Goddeeris CM nv",
"VERKINDEREN AANNEMINGEN",
"LARDOT CONSTRUCT",
"A.I.S. Steigerbouw",
"Leclercq Energy",
"FIRE SECURITY",
"LEMAIRE Parcs et Jardins",
"LEMAIRE PARCS ET JARDINS",
"EUMACS",
"SPECIAL CLEANING BENELUX",
"MAC International",
"ISCO SCAFF",
"AVISLUX",
"OCAD",
"LTC Veegwerken",
"VARYA",
"NORMEC SENSORY BELGIUM",
"ALPAS",
"Bouwonderneming CUYLAERTS",
"General Painting",
"ELECTRO - BERTELS",
"PLASTIC COVER INTERNATIONAL",
"VATIS",
"ASSAINISSEMENT ET SOIN DE VOTRE PATRIMOINE",
"OPTIWIRE",
"Synergis technische installaties",
"TCE CONSTRUCT",
"ICE",
"Maurice Verbeeck",
"ODS Belgium",
"TKN Group",
"BLUE MOON",
"J. VANDECRUYS",
"Duyalbo",
"BROSENS AANNEMINGEN",
"JOLY SA",
"ELGEBO",
"V.D.S.",
"Emerson Industrial Automation Belgium - site Muyle Electro Machinery",
"NIDEC INDUSTRIAL AUTOMATION BELGIUM",
"ERP SERVICES",
"HENNING",
"SIGGA",
"ENTREPRISES LAMBRY",
"La Connexion Téléphonique et informatique (CTI)",
"LOISEAU",
"D.P.E.DIVING",
"P.M. INDUSTRIE    SARL",
"cvd partners",
"TRAVAUX DIVERS NAMUROIS",
"RADOUX Lambert",
"GEOSONDA",
"GEOSONDA ENVIRONMENT",
"KOM CLEANING SRL",
"Hoerbiger Turbomachinery Service bvba",
"ENERGIE & AUTOMATISATION",
"RENOVATION DE.CONSTRUCTION",
"Energetic",
"GRETERCO",
"ENTREPRISES GENERALES DE TRAVAUX DU BATIMENT",
"Courrières",
"DE JONGHE",
"ENTREPRISE ROSE",
"Infratel Belgique",
"ENTREPRISE GENERALE TRAVAUX & CONSTRUCTIONS",
"ALGEMENE ONDERNEMING D'HEER",
"Algemene Onderneming Rooms",
"PROLECO",
"ATELIER A. HENRARD",
"KITCHCO",
"All Generations Projects",
"GLOBAL NEW AUTOMATION",
"BETON PETER MATTHYSEN",
"WILBOW",
"AKTIE STELLING & BOUWWERKEN",
"RENE LAMBAY ET FILS",
"VANOGROEP  N.V.",
"REKA",
"STV Métal",
"AGRIBER SERVICES SCS",
"TERRA ELEC",
"GWS",
"detech",
"AZ CONNECT",
"ABB Robotics Solutions",
"M.I.M & CO",
"Grondverzet Rental",
"VERGA",
"ALYA",
"TRYLON TSF Belgium sprl",
"C&C Projects",
"Ateliers Jean Henrard et Fils",
"VMA PROCOOL",
"Care",
"TRANSMO",
"BIESMANS ALG. OND.",
"DE SUTTER LUDO",
"ESEC S.A.",
"CKS",
"ESTIM",
"MECHANICAL MAINTENANCE COMPANY",
"Colpaart Grondwerken",
"Laureyssens",
"ENERGIE SERVICE CONTRACT",
"ALL DEMOLITION SERVICES",
"Ateliers de Constructions Métalliques A. Vossen et S. Schaus",
"GRONDWERKEN WILLY MAES",
"MAPA",
"BELGOREF",
"MANETHEC GORNIK",
"SCHEPERS",
"Dewalque-Marchal",
"RENOVATIE REMMERS",
"Wils & C°",
"T.C.S.",
"G SOLUTION CONSULTING",
"BELGIQUE TRAVAUX EN HAUTEUR",
"BROTHERS UNION BELGIUM",
"Paul Keuleers",
"INDUSTRIAL MAINTENANCE AND ENGINEERING GROUP",
"HEIDIMAT",
"COGEGAZ-FM",
"EBC Lambert",
"DE WILDE Edwig",
"Electro-mécanique Charles Meunier et Compagnie",
"INTEC",
"KOXKA BELGIUM",
"Janssens, Timmy",
"Algemene Ondernemingen D'Hollander",
"ELBIS",
"GIMOG",
"CONSTRUCTION METALLURGIQUE EUROPEENNE",
"SRL DUBOIS",
"SPEED WORKS",
"A.Q.",
"NETWERK",
"OLSEN ENGINEERING",
"GPAllied EMEA",
"C&G",
"Sambre and Industry sa",
"Global PLastiX GCV",
"Générale Maintenance Services International",
"ELECTRO - TEST",
"Callewaert Industries Technical Support",
"Callewaert Industries Construction & Engineering",
"AAM",
"Gérard Dekoninck sa - G.D.K.",
"MBS",
"BELTING",
"Building Equipment Solutions Technologies (B.E.S.T.)",
"HUBIEGROUP",
"ELGO",
"Resitec",
"@YOUS",
"ENTREPRISE ANDRE LEMAIRE",
"CONSULTING SERVICES BELGIUM",
"NETCONNECT",
"AMR",
"B.M.C.G.",
"R. Smet & Zn",
"GODART Services",
"Technogas",
"LAS-DECO",
"L. VERMEIREN",
"SIDD",
"Co-Worx bvba",
"DIRIFOR",
"ALL TECH SOLUTIONS",
"Ultimated",
"AGILENT TECHNOLOGIES BELGIUM",
"COVER",
"ELITE TECHNOLOGIES",
"Emextra",
"INDUSTRIAL MAINTENANCE AND CONSULTING",
"I.M.S. - BENELUX",
"GEOFFREY ET STEPHAN SATIN",
"VALOR SERVICES",
"Rento Boys",
"Stevens Robert",
"Etalentis bvba",
"INTERNATIONAL TANK MANAGEMENT TECHNOLOGIES",
"ESO BELGIUM",
"NETWORK CABLING SOLUTIONS",
"Laurent René SPRL",
"EGTRL SPRL",
"PCI NV",
"RCI Services bvba",
"CRM",
"STEURS Algemene Onderneming",
"MAINTENANCE TUYAUTERIE SERVICE",
"INDUSTRIELE BERLAARSE SCHILDERWERKEN",
"Fontec",
"Technique et Services Gaz",
"Esas Engineering",
"Kohnen Piping Service International",
"Beckers",
"TDD",
"HOME INVEST",
"GEOLAB",
"WAUTHIER Contractor and Trading Partners",
"CENTECH",
"Underground Solutions",
"COMPUTER INTEGRATED SURVEY SYSTEMS",
"CoSo by Arobs bvba",
"RENOBUILD",
"ETI",
"LASRI",
"SONAL",
"BPKWADRAAT",
"E.S.P.",
"AM Consulting",
"DS",
"GSA INFRA",
"A.C.A. SERVICES SPRL",
"JPA - Clean Perfect",
"Contech Project Bulgaria Ltd.",
"TECOM",
"Billen Boringen",
"ACMI  S.A.",
"YBK TECH",
"P&E DE SMEYTER",
"ENVIRONNEMENT - ECOLOGIE - CURAGE",
"ERLIN",
"DÉMO PRO",
"GITI GH",
"ALV",
"Navicom",
"SERVICE COMPETENCE CENTER",
"VINK",
"R+",
"CARE et CURE",
"Sensor IDS",
"WTS",
"HOLDING VAN HAUTE CEYMEULEN",
"W.T.S. NV",
"DEFRAINE MANUTENTIONS",
"G.N.O.",
"Polygon Belgium NN",
"ss group",
"Vega",
"MOLDSTAL",
"DE GROOTE André & Zoon",
"VERHELLE",
"E.D.L.",
"FLANDERS TECHNICAL SUPPLY INTERNATIONAL",
"NIJS PIPING",
"RISBEL",
"HUYGHE F & D",
"B-CORE GROUP",
"Demaco Piping",
"LAD",
"Spectron Bouwchirurgie",
"VENSOL INFRA",
"L.ECL",
"Binnebeek Paul & C°",
"AWAH",
"IMMO CAELEN",
"ISOTHERMIC ECHAFAUDAGES",
"PAUWELS & ZN.",
"Industrial Maintenance Company",
"S. Schrauwen en Zn BV",
"Renato Construct bvba",
"Exyte Central Europe GmbH",
"URBAN PROPERTY",
"ISOPRO",
"TECNO ART",
"SEB PROFESSIONAL BELUX",
"ETECH",
"SPRL WIDRA",
"VERENIGING BUREAU VERITAS - ASSOCIATION BUREAU VERITAS",
"STORMBEE Europe",
"CIBOR",
"CIRCET BELGIUM",
"I.D.C. Boringen",
"FBM industrial services bvba",
"GEBO",
"CVR",
"GILLIS",
"CONDUITES ET CABLES ENTREPRISES",
"JB Plates",
"INTERBAT",
"KRAANBEDRIJF D.BUERMANS",
"EPSILON PAINTING",
"G.P.R. ATELIERS GOFFIN",
"APRO",
"DVL Constructions BVBA",
"CALLEWAERT",
"EUROPE CLEANING SERVICES",
"THOMAS CONSTRUCTION",
"ROSSIE WELDING SERVICES",
"Veolia WTS Belgium",
"MAINTENANCE INDUSTRIELLE REMY LUCIEN",
"PUTBORINGEN VAN HEUGTEN MARC",
"MAPI-ELEC",
"TRADILO",
"COSMO",
"Euro Fire Group",
"Terram Sud",
"PROMOUVOIR LA SECURITE",
"MIRA NEF",
"GoXL BVBA",
"RENE LEONARD",
"ELECTRICITE GENERALE COLLIGNON",
"Dadigro",
"LIBAN",
"a.dk. - MOVES DEKEMPENEER",
"FAILSAFE",
"BOX 43",
"CONNEXION FOBELETS TRAVAUX",
"CONNEXION FOBELETS TRAVAUX",
"Centre de Recherches de l'Industrie Belge de la Ceramique",
"D.S.I.",
"FARRIS Antonio",
"AS.M.",
"Omega Plus Construct",
"PRO BUILDING TECHNICS",
"Nitra+",
"IFSC",
"KENIS",
"ARAD",
"VAN FRONTBERGHE",
"DM & C GROUP",
"AFSAM",
"BELGOKABEL",
"BMS SYSTEMS",
"Risan",
"E²S",
"HARBI",
"Eurofins Asbestos Testing Belgium",
"SEVOBU",
"SCRAP METAL SERVICES BELGIUM",
"CLEAN PARTNERS INDUSTRY",
"Willems",
"Building and Industrial Topographical Services",
"PROFIL",
"LUMET TRANSPORT LOGISTIEK",
"Jansen Energy Solutions",
"STROPPA",
"AG GRONDWERKEN",
"SUELGA",
"M.S.B.",
"REMOTEC",
"EM GROUP",
"KBS-Systems",
"AMERY",
"Rooms",
"DNCS",
"THEIA",
"Interconnection B.V.B.A.",
"MZN Grondwerken",
"MCT",
"Remotec",
"PLATEX",
"Dogan Cleaning",
"EUROMAT-GENT",
"DE BOCK & CO",
"METAPLASTITUBE",
"HAIRSTATION AYDIN",
"L.M.C.",
"WELDESIGN",
"RAILCONSTRUCT",
"Aksoy-Dogan Infrastructuur",
"EUROPEAN COMMUNICATION NETWORKS",
"SKYY",
"TEC",
"EGD",
"JOHN CRANE BELGIUM",
"CME TUYAUTERIE",
"Deufol Port of Antwerp NV",
"EKU ALGEMENE ELEKTRICITEITSWERKEN",
"EDA",
"N&N Cabling Fiber",
"Alitech",
"ECO - PLANNING",
"DKE",
"MAINTENANCE TUYAUTERIE SOUDURE INDUSTRIELLE",
"Eazer Facility",
"ENERSOL",
"MS.GROUP",
"Industrial Valves Repair & Services",
"T.M.C.",
"Primo Services - afdeling Stellingbouw",
"First Team - Afdeling Stellingbouw",
"Evon",
"MEGAMAX",
"MEG",
"Van Goethem & Co",
"Association des Propriétaires de Récipients a  Gaz comprimés, liquéfiés ou dissous",
"Mertens en Zoon bvba",
"AV Controlatom",
"ENTRETIEN INDUSTRIE SERVICE",
"THT Bouw Spolka z.o.o.",
"ASTERIX",
"CV KEERMAN",
"Full House",
"NITRA",
"MONTEC",
"EDITECH ENGINEERING",
"Traffic Services",
"ACCEDE",
"Lu-Elec sprl",
"GEFOR",
"MAINTENANCE, ROBINETTERIE, TUYAUTERIE INDUSTRIE",
"TEKSOL",
"ENVIROSOIL",
"Envirosoil",
"Castolin Eutectic Benelux",
"D.S.P.",
"HYDREX",
"ECODREAM",
"Endress et Hauser",
"CLEANING PROFESSIONALS",
"APS",
"UG INDUSTRIAL",
"Constructions métalliques Julien",
"B INVEST",
"DK ELECTRIQUE",
"JVB Technics",
"Energies et Services",
"Esas Field Services",
"IIT BELGIUM",
"EDK ELECTRIQUE",
"AIR MASTERS",
"ANZA CONSTRUCT",
"Renders Tuinen",
"BMT SOLUTIONS",
"Kraanbedrijf Gebr. GOEYVAERTS",
"CLIMAIR",
"MECHANIC COLD PULLING BELGIUM",
"METALEN EN NIET-METALEN DAKINSTALLATIES",
"S.T.I.",
"Essent Milieu Belgium",
"EURO ISOLATION ISOTHERMIC",
"RTA",
"de KOCK",
"PG SERVICES",
"ARGOS INDUSTRIAL",
"ESS",
"Firma Cornelis-Wauters",
"BETON en ASFALT  CONSTRUCTIE Naamloze Vennooschap",
"Télé Technique Générale SA",
"Firma DOBOS J.",
"GUNCO nv",
"GLOBAL GRINDING",
"OR DEMOLITION",
"GREEN MASTERS",
"T.T.G.",
"Farinha da Silva, Jose",
"P.F.L.",
"GREBAT",
"GERMONPRE",
"EMEK",
"ESPACE CLEAN",
"ALGEMENE ONDERNEMING R. DE ROECK",
"LM ENGINEERING",
"AIRCONDITIONING KOELTECHNIEK VAN EESTER",
"AVAM",
"VERSCHUEREN",
"SCHILDERWERKEN W. VAN GOETHEM",
"EMEGA",
"CRIC",
"MICHEL - LAMBERTY",
"Orti",
"@ FEE DU PC",
"MINERALEN KOLLEE",
"3D-Lift",
"MARULLO ENTREPRISE",
"EH GROEP",
"E&H PROJECTS",
"Geka Pomping",
"HARONDAK",
"CASSIUS 3",
"SERVICE PARTNER",
"Van Elsuwege",
"BK-Interior",
"SMART ENERGIE",
"PELZER",
"GOZEN",
"KRIEKEN",
"CLEAN TECH",
"Metaplast",
"GMA ELEC",
"GUN",
"DISTRIFIBRE",
"GWL",
"LAMEIRE Special Technics",
"FAMI",
"Dadrigo",
"ELEANTIS",
"KEBRO",
"KBS CONSTRUCT",
"TSR GROUP",
"ISIS Construct sprl",
"GLOBAL MAINTENANCE-INDUSTRIES",
"NEW ENERGY",
"DMI CONSTRUCT",
"PM GROUP BELGIUM SERVICES",
"Meka-Nord",
"E.M.P. Company",
"GEBROEDERS DIRIX",
"METALYS",
"DE MULDER CONSTRUCT",
"D.M.A. SALE & RENT",
"Entreprise Générale de Construction VANDEKERCKHOVE",
"NGTECHNICS",
"INTERMONT",
"VAN HOOF & co",
"EURO - SERVICES",
"ENERGY TEAM",
"ALGO",
"Ets. VAN BELLE M.",
"Bouwonderneming R,Maes NV     Alg. Onderhoudswerken Maes NV",
"Grondwerken Plaquet",
"Grondwerken Plaquet Robert",
"GIMAT",
"GRODÉVÉ",
"Etablissements L. Warichet",
"SK Industries",
"SEMAT",
"Entreprises HALLOY",
"WELDMEN",
"ALP NET CLEAN",
"Entreprises François Polis S.T.R.A.M.I.N.G.",
"NV Electriciteit Vandenheede Industrie",
"Travoma",
"ENT. VISINTIN",
"B&W ENGINEERING",
"U2 POWER SOLUTIONS",
"VAN RAAK LOUIS",
"Theeuwes Technische Installaties",
"Tuyauteries Industrielle du Hainaut",
"L.M.C. SRL",
"Blue Waters Engineering",
"E.T.H.",
"SOCOMAT",
"GS SOLUTIONS",
"TOOLS",
"TEGRO",
"Belsah",
"Applications Thermiques",
"UNIZON",
"HMY TECHNICS",
"VDE Metaalkonstructies",
"NetTech",
"TCS Graafwerken",
"CONTECH ELECTRICAL SERVICES",
"M.B.S.CONSTRUCTIONS SPRL",
"GESCO",
"JANSEN BUILDING SOLUTIONS",
"Ondernemingen Johan Meijs",
"DEVILLERS",
"All Hytec bvba",
"M.D. TECHNOLOGY",
"ELTI BOUW",
"IMAF",
"ADVIES, ONTWERP EN REALISATIE VOOR DE METAALVERWERKENDE NIJVERHEID",
"TRANSTONE",
"Kiran",
"BOPLAN",
"ENTREPRISE BAGOT",
"Algemene Metaalbouw AMB",
"COLLAERT FRANK, algemene bouwonderneming n.v.",
"MARAITE BERNARD",
"D’hooghe Lifting & Transport",
"HERCON",
"FAER",
"MEUNIER IMMO",
"Han",
"POLYTHERM",
"LOCAHERTS",
"ROEFS CONTAINERS",
"Invest CB",
"GEA WESTFALIA SEPARATOR BELGIUM",
"MONTEYNE",
"GWinvest",
"EDA BE General Electricity",
"LES TRAVAUX EXTERIEURS",
"SARITEC",
"CALISOL",
"AERTSSEN INDUSTRIAL SERVICES",
"Environ Engineering NV",
"I.D.C. & Co",
"Swinton",
"SIDERBA MECHANICAL",
"Profix Group",
"Construct Masters",
"Altrad Balliauw Group",
"DAKWERKEN COSTERMANS",
"SIDERBA EUROPA",
"ERAS Belgium",
"SKYWORKERS",
"AXYZ Chemical Cleaning",
"GROUP SKY",
"SIEMENS N.V. Industry Solutions – Project Execution & Engineering (IS PE) – Services & Maintenance (IS SM) – Industrial IT (IS IT)",
"BTS CONSTRUCT",
"Petroleum Products Storage and Transports Company",
"HYE",
"CLEANING MASTERS",
"Akkodis Belgium",
"LEENDERS",
"INALCO",
"ATLAS COPCO RENTAL EUROPE",
"BUIJSSE SPECIALS",
"HEGO",
"Wood Italiana",
"Siderba Continental",
"T.D. WILLIAMSON BENELUX",
"Fa Leffer & C° Kg",
"SECURITY MASTERS",
"INDUSTRIAL COMPANY OF TECHNICAL SOLUTIONS",
"Alstom Thermal Power Belgium S.A.",
"MSI GROUP",
"Belcotec Technics",
"AG Solutions",
"Fast Connect",
"KF DIGGERS",
"Xper NDT",
"DIVA CONSTRUCT",
"Gent Invest Groep",
"R & M",
"Schepers, Carlo",
"OF SERVICES",
"NS DYNAMIC",
"CILDIR CONSTRUCT",
"EL HOUJE'S",
"2MM PROJECT",
"FOURTECH",
"BENELUX CONSIN",
"John Cockerill Hamon",
"EENHEID LASE",
"F&C TECHNICS",
"DE-MA",
"DSA Infra",
"ASinfra Belgium",
"KONING",
"Climt International",
"ILLUMINATION DESIGN AND DEVELOPMENT",
"U-STORAGE",
"Solutions 30 Belgium",
"OMECA ENERGIE",
"LIMGAZ",
"A.G.E.C  Construct",
"S.AIR",
"POWERTECH",
"UXOM",
"GPC Cabling Systems",
"TECTUM PLUS",
"ECOLECTRIC",
"REMI",
"ADS.HU",
"ADA Services",
"Bullgaz BVBA",
"Thomas & Piron Bâtiment",
"FLEURINVEST - Filiale du Groupe Wallindustrie",
"G.D.V. ALGEMENE BOUWONDERNEMING",
"ENTREPRISE DEVRESSE",
"MACLOT-GC",
"DPS Concept",
"MDO GROUP",
"QUICK RESTAURANTS",
"INEXCO Bouwservice NV",
"MOBIX",
"HEINEN S.A.",
"ENTREPRISE JEROUVILLE",
"Fabrieksschouwenonderneming Frans Eyckmans en zonen",
"ONET BELGIUM - Agence Wallonne - Herstal",
"ALMECO",
"WOONINRICHTING TAPIGRO",
"ONEFIELD ICT",
"RENE CLAEYS",
"Altrad Logistics Benelux",
"HOUBEN",
"ENTREPRISE MARCEL BAGUETTE",
"Constructies VERCAIGNE",
"CABLING STATION DATA",
"GLOBAL CARE-ION I",
"ROEFS",
"HERKULES",
"GDD INFRA",
"CONSTRUCTION & MAINTENANCE DE LIEGE",
"BELTEK",
"EDF Renewables Services Belgium",
"OMNI-DRAIN",
"INTERNATIONAL CONSTRUCTION TACTICAL",
"Calagan, Adnan",
"IMMOBILIERE REP'R",
"DKT-Projects",
"BKA Service, providing the best service in industry",
"TECTUM DEKKERS SUD",
"LAURENTY ESPACES VERTS - GROENE ZONES",
"DC Klima thv",
"NOUVALL ENGINEERING SERVICES BELGIUM",
"G.T.M.",
"Maintenance Masters",
"AANNEMINGEN REMIGRO",
"CBRE GWS Belgium",
"BESIX Unitec Automation",
"GEYSEN HO",
"MONO-INFRASTRUCTURE",
"Ufficio 2.0 BE",
"M-SYSTEMS",
"DRILLING SOLUTIONS",
"TALENCO",
"EMS Floor Belgium SRL",
"Future Foundations",
"DB Welding",
"MB Tech",
"N.V. Quireyns Algemene Ondernemingen",
"BKC",
"O.C.O TECHNICAL",
"ALTURA ACCESS",
"MYMO",
"M.D.TRUST BELGIUM",
"STS D&V",
"QBC",
"Future Services Int.",
"LYBOTECH",
"SMET GWT EUROPE",
"UNIRENT",
"Maintainability & Availability without Hazards of Infrastructures",
"FOR U SERVICES",
"A-NET",
"PROFERA",
"POLATT BVBA",
"Protectum BV",
"MS-INFRA",
"#Perfect Finish Asbestverwijdering",
"Nemac",
"Hitachi Energy Belgium",
"Electro Services Eerdekens",
"DEME Offshore BE",
"DOSAL TECHNICS",
"HIBER TECH",
"DCA INFRA",
"DSS Infra",
"BRETECH",
"IMMO TGC",
"BEA Tecnics",
"Asbest 2 Remove",
"YATECH",
"FlexSol",
"JEMISOL MONTAGE",
"PLAN A2O",
"INFRATECHNICS",
"A-Connect",
"M.H MOTION GROUP",
"DL-Infra",
"TRK Infra",
"Modern Renovation Technics NV",
"Mebumar België",
"Algemene Aannemingen Grond- en afbraakwerken Jan Stallaert",
"EUROCLEAN",
"Belgacom nv, Afdeling IFM",
"Smet-GWT",
"Profix Services bvba",
"Smet Pile",
"Francis & Tytgat",
"TIMMERMAN Gebrs.",
"Compagnie Générale des Asphaltes",
"VMA VANDERHOYDONCKS",
"Laboratoire belge de l'Industrie Electrique",
"CETRA",
"MONTACENTRE",
"Colt International Belgium",
"SIGN & FACADE LIEGE",
"Entreprises Cop et Portier",
"Entreprise générale  MOUREAU François et ses fils",
"FRANKI",
"Emi (Electric and Musical Industries Belgium)",
"Gravo",
"Colas Noord",
"ETEC",
"PACKO COOLING",
"Gebroeders De Waele",
"LOUIS DE WAELE CONSTRUCTION",
"SOCIETE DES TRAVAUX GENERAUX DE CONSTRUCTIONS",
"VEREECKE",
"JAN STALLAERT",
"Mobix Stevens",
"Bouwbedrijf Emiel Dillen",
"Marcel Nijs",
"Worley Belgique",
"VANSTEENKISTE INFRA",
"FLUENTIS",
"Johan Platteau",
"THE BELGIAN",
"S.A. ETABLISSEMENTS LEON CROSSET",
"VK GROUPE",
"DEME Environmental",
"DC Onsite",
"STRATICA",
"Proaccess",
"AQUASTRUCTO",
"TELCOM",
"HUFKENS Algemene Schrijnwerkerij",
"MAES",
"EEG",
"F. Van De Cappelle & Zn",
"HBS",
"PCA",
"QUBUS",
"JASCO RENTING",
"GALLIPOLI",
"ITB",
"TK Elevator Belgium",
"SIVERMA",
"Barré",
"DE WITTE",
"BOUWBEDRIJF WARSON en CONSOORTEN",
"FEXIM",
"Mobix Remacom",
"METIS",
"BESIX Connect",
"ARONIA",
"DYNATHERM",
"DELOTER SA",
"DTO",
"SHANKS BELGIUM",
"P.C.T.",
"SOCIETE ATHOISE DE TRAVAUX",
"ATALIAN",
"ALGROBO",
"ELECTROBUILD",
"A.V.M.",
"KLEEN DAILY",
"New CCD - Filiale du GRoupe Wallindustrie",
"CSB²",
"UNION MULTISERVICE",
"E.C.V",
"HYLINE",
"APK CONSTRUCT",
"FINES",
"BERNARD CONSTRUCTION",
"STABIL",
"CMI TRACTION",
"KORLAM",
"AKSIS INTERIEUR EN BOUW",
"M.D.C.T. BENELUX",
"Techma Nord",
"DEBINCO",
"DELTA MAINTENANCE",
"SOCIETE HENNUYERE DE MONTAGE ELECTRIQUE",
"KSB Service Belgium",
"ALOCA",
"H. DE COCK",
"ABBA",
"VERDON",
"BOUWONDERNEMING KERSTENS",
"Etablissements DEMOL",
"VMA be.Maintenance",
"André Audenaert",
"ATOX",
"CHUBB SECURITY SYSTEMS",
"Travaux Voiries et Conduites",
"ICOMET DV",
"Lambrechts Willy N.V.",
"TERRES REFRACTAIRES DU BOULONNAIS MESLES",
"DIERICKX FRANCE",
"Vranken",
"DAGO",
"SCINORTEG NV",
"GTS s.a.s.",
"Telenet Business Solutions",
"DC INDUSTRIAL",
"TUMAR",
"ISOREF",
"WINSOL",
"CORDEEL ZETEL HOESELT",
"Coussée Bouw",
"ELECTROTECHNIQUE ET MECANIQUE DE TERTRE",
"VMA SUD",
"DEBEUCKELAERE ELEKTRO",
"SOCIETE SPECIALISEE EN TUYAUTERIE ET MECANOSOUDURE",
"Mobix Engetec",
"TECHNO SERVICE",
"DEPANNAGE DE GROOTE",
"SMET-F & C",
"GOEMINNE J. & G.",
"Tube Industrie SA",
"GENERAL TECHNICAL SERVICES FOR PROJECTS",
"VCM Metal",
"DEME OFFSHORE HOLDING",
"EXECON",
"ICOMET",
"GKW",
"Compagnie Luxembourgeoise Industrielle Montage Tuyauteries Belgium",
"GEUKENS LUC",
"ELEKTRICITEITSWERKEN DEBAELE ANDY",
"DELTAXO",
"ATLAS FONDATIONS SAS",
"Haronique Vastgoed",
"Geo Engineering",
"BSB HANDLING",
"De Baets, Johan",
"DELTA GROUP",
"SIGN & DISPLAY",
"VMA Antwerpen",
"SHANKS Vlaanderen - Divisie Roeselare",
"GEBRUDER PETERS INDUSTRIETECHNIK",
"iServ BV",
"Pumps and Projects BV",
"IMMO VIE NOUVELLE",
"ALTEBRA WAREGEM",
"ELECTRABEL RENEWABLES BELGIUM",
"MBG - Zone Noord",
"Logi-technic Infra - Deerlijk",
"ENGEMA Lignes",
"ENGEMA Montage",
"Engema Rail Bovenleidingen en Rail Seininrichtingen",
"BAM Contractors - Nazareth",
"Logi-technic - Zwijndrecht",
"BAM Contractors - Sint Truiden",
"MBG (NOT TO USE)",
"Logi-technic Building - Vilvoorde",
"TyssenKrupp Liften Ascenseurs",
"ACOTEC",
"altez  Oost",
"NEOTEC",
"CONSTRUCTELMODAL",
"BAV",
"KOOLE",
"MBG",
"Blomo bvba",
"Aertssen Infra",
"SIDERBA EUROPE",
"TECHNORD BELGIUM",
"JOHN COCKERILL SERVICES HAINAUT",
"COOLTECH",
"INTERSEAL",
"DIGITAL SOIL FACILITY MANAGEMENT",
"TUBE BELGIUM",
"HD Systems",
"Modus Industries",
"B-MOREHR",
"DEME Dredging",
"VYTECH ZELE",
"VEMA",
"F I B SERVICES GROUP",
"FG-Software",
"UÈMECÉ",
"Kopman Interim bvba",
"ABSOLUTE@WORK",
"RUNTIME",
"Dirickx, Jan",
"Safety First Belgium bvba",
"STRABAG BMTI BVBA",
"TRIXXO JOBS I",
"CEPESI ASBL",
"USIT",
"ADECCO CONSTRUCT",
"Construct Interim",
"Algemene Bouwservice",
"Quality Jobs@work",
"PROGRESS GROUP",
"PAYROLL SOLUTIONS",
"Tytgat, Sander",
"De Roeve Installations",
"Triangle solutions RH construction",
"BUSINESS SOLUTIONS 30 BELGIUM",
"JOBZ",
"ESE.roof",
"S.M. SYSTEMS",
"Daniel Bodson",
"THE BOZZ",
"Masters",
"ADMB Interim",
"T GROEP",
"Accent Jobs for people",
"Trace S.A.",
"Impact Interim NV/cleaning & contracting",
"Agglocim SPRL",
"UNIQUE",
"Randstad Belgium",
"ADECCO PERSONNEL SERVICES",
"Rijks Aannemings- en Handelsbedrijf",
"ASBL Metalgroup ETA",
"Dakwerken Van Mechelen P.",
"S-MI",
"GSF",
"BEPHONIC",
"EEG, Divisie Van Braecke",
"Cleaningboy",
"LENAERTS",
"EQUIP'",
"VYTECH MENEN",
"impasto",
"Start People",
"Timmerwerken Van Mechelen P.",
"SYNERGIE BELGIUM",
"Liantis talent services",
"LET'S WORK",
"IMPACT",
"NETSITE",
"Algemeen Bouwbedrijf Muermans",
"Marcotech BVBA",
"Transport STB",
"C & M",
"ETABLISSEMENTS D.S'JONGERS",
"EXATEC sprl",
"FLEXPOINT",
"INDUSTRIE NOUVELLES TECHNOLOGIES",
"JOBMATCH",
"LEPAGE EURONUCLEAIRE",
"Veolia Environmental Services Wallonie",
"Sala & Fils",
"Ferométal",
"Nadin Immobilière",
"CARRO-GRES",
"GASON",
"Bernard Facon",
"Winbalu",
"Wanted Belgium",
"B.M.C.",
"AGO CONSTRUCT",
"ACS Trading bvba",
"KEYWORKS",
"SAMENWERKING TECHNIEK ORGANISATIE BELGIUM",
"H&D Projects",
"Konvert Interim Brussels",
"KONVERT INTERIM Wallonië",
"Accent Construct NV",
"E.I.L. Technieken",
"Construct Aalst",
"Sulo Nederland Nieuwegein"
]

request_counter = 0
requests_per_session = 50 # Number of requests before a long wait
long_wait_time = 30 * 60  # 30 minutes in seconds

with open('company_websites.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(["Company Name", "Website", "Tries", "Company Name on Gouden Gids"])
    
    for company in companies:
        row = get_company_website(company)
        writer.writerow(row)
        request_counter += 1
        print(request_counter)
        # Check if the counter has reached the limit
        if request_counter % requests_per_session == 0:
            print(f"Completed {requests_per_session} requests. Pausing for 30 minutes...")
            time.sleep(long_wait_time) 
        print(row)

print("CSV file 'company_websites.csv' has been created successfully.")